### ISSUE TITLE
O(n!) complexity for combinatorial complex 

### ISSUE THREAD

**Issue by bahramiramazan** [pyt-team/TopoNetX#107]
If you create a combinatorial complex , and try to add a cell of  cardinality greater than 17, and rank 1 , you will notice that  it takes a very long time. if you reduce the cardinality  of the added cell it gets lesser  and lesser time to add it into the cc, and if you increase the cardinality  , it will take   longer and longer to add the cell. 
My point is , add_cell has a time complexity o(n!)  ,as for every set , it considers all possible combinations. I could reduce this to linear , by modifying  some parts in my fork  , but I am not sure of the consequence of these modification  for behaviour that I have not tested. incidence matrix and and adjacency matrix were working as they should.

**Comment by mhajij** [comment]
Indeed that is one of the main issues in CC! it creates the closure of a SC for the speed of add_cell but on the cost of scalability. I am gonna work with you on addressing this issue.

**Comment by USFCA-MSDS** [comment]
new implementation of CCC takes care of this complexity by creating memebership of every node.
