### ISSUE TITLE
Documentation is already updated for open pull requests

### ISSUE THREAD

**Issue by ffl096** [pyt-team/TopoNetX#113]
As of right now, the changes of my pull request #112 are already visible on [the documentation website](https://pyt-team.github.io/toponetx/api/classes.html#module-toponetx.classes.simplicial_complex) even though the pull request has not been merged yet (see also when https://github.com/pyt-team/pyt-team.github.io/commit/bc604e2 as authored). This most definitely should not be the case.

The problem is that the docs workflow is [triggered on pull requests](https://github.com/pyt-team/TopoNetX/blob/749e258e2c62a1d6cb5483ee20185612151e6101/.github/workflows/docs.yml#L6) as well. This is fine for most steps of the workflow to test that Sphinx can build the documentation according to the pull request. However, the last step should only be executed for actual pushes to the main branch.

**Comment by ninamiolane** [comment]
Indeed! Thank you for catching this 🙌  @ffl096 any chance you have the bandwidth to address this?

**Comment by ninamiolane** [comment]
Nevermind, I got it! ;)
