### ISSUE TITLE
Mix of ordered and unordered data structures

### ISSUE THREAD

**Issue by Hellsegga** [pyt-team/TopoNetX#154]
The following example leads to an error:

```
from toponetx import SimplicialComplex as sc

simplices = [[3668, 5308, 5900]]
SC = sc(simplices)
B1 = SC.incidence_matrix(2)
```

The problem if I'm not mistaken is a mix of ordered data structures (tuple) and unordered (fronzen set):
- SimplicialComplex._simplex_set contains simplices as sets
- But in SimplicialComplex.skeleton function the simplices are converted to tuples
- In SimplicialComplex.incidence_matrix the faces are taken by set difference and converted to tuple, but this may not match the keys of the structure returned by SimplicialComplex.skeleton

**Comment by mhajij** [comment]
- The incidence matrix must have a canonical order for the k and k-1 skeletons. So hence ordering things is important to make sure we have that canonical all over the matrices defined in the complex. This is particularly important when defining data on the complex.
- The order is inherted from SimplicialComplex.skeleton which is chosen to be a dictionary order. Hence converting the set to tuple is important.
