### ISSUE TITLE
Minimum Python Version

### ISSUE THREAD

**Issue by ffl096** [pyt-team/TopoNetX#161]
Minimum Python versions are kind of a mess across all packages:
- TopoNetX is Python 3.9+
- TopoEmbedX and TopoModelX are Python 3.10+

Moreover, the Python version in the README files is wrong:
- Even though TopoNetX is 3.9+, the README claims 3.10 is required.
- Even though TopoModelX is 3.10+, the EADME claims 3.11 is required.

Lets decide on a minimum version that applies to all three packages and fix the README files accordingly.

**Comment by ffl096** [comment]
I would say to at least support Python 3.10. Dropping 3.9 comes mostly down to some typing features that are not strictly necessary but are nice-to-have.

**Comment by ninamiolane** [comment]
Agreed, let's do 3.10
