### ISSUE TITLE
Discrepancies across sparse tensors: csr and coo

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoNetX#166]
The neighborhood matrices, (incidence, adjacency, etc) are often sparse.
Depending on the function, the matrix returned is in sparse COO or sparse CSR format.

Is there a good reason to have this discrepancies in formatting? If not, let's convert everything to either coo or csr, because other downstream algorithms would enjoy knowing that a consistent type is returned.

**Comment by michaelschaub** [comment]
As COO ist not a format for downstream computation but just for construction of matrices.
(see intended usage here https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html)
The output should be csr (or csc), in my opinion
