### ISSUE TITLE
Source Links in tutorials don't work

### ISSUE THREAD

**Issue by devendragovil** [pyt-team/TopoNetX#177]
# What?

Source links in tutorials don't work. Example:

<img width="611" alt="image" src="https://github.com/pyt-team/TopoNetX/assets/39613474/1622ba47-1ac6-460a-beb8-d23d03adad74">

# Why?

It is important for people to go back to the actual notebook and download.

**Comment by USFCA-MSDS** [comment]
@devendragovil , what do you mean it does not work?
