### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by jackychen08** [pyt-team/TopoNetX#240]
Hi, I am confused by the documentation/definition of the incidence_matrix function in cell_complex.py. It's not clear to me whether the function calculates an up-incidence matrix of rank r, a down-incidence matrix of rank r, or if there is a way to use the function to calculate a (r,k)-incidence matrix. 

For instance, if I had a cell complex with cells of rank 1,2,3 corresponding to nodes, edges and faces respectively, what would be the best way to calculate the (2,3) incidence matrix to see which edges are incident to faces?

**Comment by mhajij** [comment]
cell complexes do not support ranks beyond 2. The incidence matrix in a cell complex takes a signle parameter, as it is supposed to be the linear rep of the boundary map in algebraic topology.

For inststance CC.incidence_matrix(1) computes the incidence between 0 and 1 rank cells (nodes and edges). incidence_matrix(2) computes between edges and faces.

If you want to go for node and face incidence then you are looking for set-based incidence which is suported in combintorial complex or colored hypergraph. Hope that helps.

**Comment by mhajij** [comment]
@jackychen08 > cell complexes do not support ranks beyond 2. The incidence matrix in a cell complex takes a signle parameter, as it is supposed to be the linear rep of the boundary map in algebraic topology.
> 
> For inststance CC.incidence_matrix(1) computes the incidence between 0 and 1 rank cells (nodes and edges). incidence_matrix(2) computes between edges and faces.
> 
> If you want to go for node and face incidence then you are looking for set-based incidence which is suported in combintorial complex or colored hypergraph. Hope that helps.

**Comment by jackychen08** [comment]
Thank you for the clarification!
