### ISSUE TITLE
Make code coverage above 90% on TopoNetX (because of JMLR requirements)

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoNetX#246]
# What?

JMLR requires that unit-tests' code coverage is "close to 100%". See: https://www.jmlr.org/mloss/mloss-info.html

We can see that, currently, it is at 86%.

![Screen Shot 2023-09-19 at 10 20 47 AM](https://github.com/pyt-team/TopoNetX/assets/8267869/f2726786-2e61-4249-8b77-162b39bb3de1)

We should make it >90%.

# How?

Go to the code coverage page for TopoNetX and observe which lines of code are not tested. Write tests for them.
https://app.codecov.io/gh/pyt-team/TopoNetX

**Comment by ninamiolane** [comment]
@gurug-dev any chance you could help with this?

**Comment by mhajij** [comment]
@maneelusf @gurug-dev

**Comment by ninamiolane** [comment]
Also see issue #256

**Comment by ninamiolane** [comment]
@gurug-dev No hard deadline, but Wednesday September 27th would be great. thanks

**Comment by gurug-dev** [comment]
PRs -> #259, #254 increase test coverage back to 90%.

**Comment by ninamiolane** [comment]
Yes! Thanks.
