### ISSUE TITLE
Change thumbnail of ColoredHypergraph tutorials on doc website

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoNetX#250]
# What?

Every tutorial on toponetx's doc website has a thumbnail. Currently, the tutorial on colored hypergraphs uses a hypergraph thumbnail. This should be corrected with a colored hypergraph thumbnail.

# Why?

Otherwise, it is incorrect and confusing for users who might mix up hypergraphs and colored hypergraphs.

**Comment by devendragovil** [comment]
@mhajij  I would like your advice on how should I visually depict a colored hypergraph.

**Comment by devendragovil** [comment]
@ninamiolane @mhajij I am thinking of how would you like me to depict the colored hypergraph. Would just shading some hypergraph cells with different colors be sufficient?

**Comment by mhajij** [comment]
@devendragovil I'll send you something later today

**Comment by devendragovil** [comment]
@mhajij @maneelusf Please send me the thumbnail for the CHG tutorial.

**Comment by ninamiolane** [comment]
@mhajij @maneelusf @devendragovil what is the update here?

**Comment by USFCA-MSDS** [comment]
@maneelusf can you please close this issue as soon as possible?

**Comment by devendragovil** [comment]
This has been completed by changing the thumbnail.
