### ISSUE TITLE
Increasing code coverage for toponetx to 99%

### ISSUE THREAD

**Issue by mhajij** [pyt-team/TopoNetX#256]
### What? 

Increase the code coverage for TopoNetX, making it ready for publications.

### How ?

The following classes require attentions as they have many methods that remain untested:

* ColoredHyperGraph
* CombintorialComplex
* CellComplex
* reportview
* Simplex

**Comment by ninamiolane** [comment]
This complements issue #246

**Comment by mhajij** [comment]
@gurug-dev any update on this ?

**Comment by gurug-dev** [comment]
@mhajij will be adding a PR this weekend to address this.

**Comment by ninamiolane** [comment]
We are not at 99% but we are very close, and I think it is enough for now. Closing it, awesome work everyone!
