### ISSUE TITLE
adding issues in ColoredHyperGraph and CCC

### ISSUE THREAD

**Issue by mhajij** [pyt-team/TopoNetX#268]
Find issues in ColoredHyperGraph and CCC, document them properly.

**Comment by mhajij** [comment]
@gurug-dev I was expecting some tags last week, I have not seen any although you mentioned you spotted issues even before our last meeting.

**Comment by gurug-dev** [comment]
Hi professor, I had observed a few issues with node_attributes set and get for cell, edge etc, but with your recent commit they seem to be fixed. adding a small test case to capture the working behavior. Will add issues if I spot any new ones.

**Comment by gurug-dev** [comment]
#288 affects remove_singletons, restrict_to_cells. restrict_to_nodes also might require looking into.
