### ISSUE TITLE
BUG in get_rank method in ColoredHyperEdgeView

### ISSUE THREAD

**Issue by gurug-dev** [pyt-team/TopoNetX#277]
## What: 
Methods have unreachable code or bugs that are potentially causing inconsistent or unexpected behaviours.

## Where:
ColoredHyperEdgeView, get_rank method
```
     elif isinstance(e, str):

            if frozenset({e}) in self.hyperedge_dict[0]:

                return 0

            else:

                raise KeyError(f"hyperedge {frozenset({e})} is not in the complex")
```

Unclear implementation and handling of str objects, any combination of hyperedge elements of rank 1, rank 0 do not get recognized and throw keyerror.
`frozenset("1") == frozenset({'1'})`, hyperedge_dict contains elements like frozenset({1}) or frozenset({1,2})

**Comment by ffl096** [comment]
> no object would be both non-iterable and non-hashable.

This is false. We are talking about data that comes from outside of our control here. They can very well be non-iterable and non-hashable.

**Comment by gurug-dev** [comment]
> > no object would be both non-iterable and non-hashable.
> 
> This is false. We are talking about data that comes from outside of our control here. They can very well be non-iterable and non-hashable.

Updated.
