### ISSUE TITLE
Clarification of order-preserving rule for CCC

### ISSUE THREAD

**Issue by viyx** [pyt-team/TopoNetX#315]
Hello, I can see in documentation about CCC

> 

$[1]$ Let S be a non-empty finite set and $\mathcal{P}(S)$ its power set. A combinatorial complex (CCC) is a tuple $(X, \imath)$ formed by a set $X \subset \mathcal{P}(S)$ \ ${\emptyset}$ together with a rank function $\imath : X \rightarrow \mathbb{Z}^+$
that 

&emsp; (i) $\imath$(${x}$) $= 0$ for all $x \in S$, and 

&emsp; (ii) for all $x, y \in X$ , if $x \subsetneq y$ then $\imath (x) < \imath (y)$.

So, we can't add cell `c2` of rank `2` if there is a cell `c1` of rank `1` which have all nodes of `c2` and more.

But I try this code
```python
from toponetx.classes import CombinatorialComplex as CCC

example = CCC()

example.add_cell([1, 2], rank=2)
example.add_cell([1, 2, 3], rank=1)

example.cells.hyperedge_dict
```
and get contradiction in output
```
{2: {frozenset({1, 2}): {'weight': 1}},
 0: {frozenset({1}): {'weight': 1},
  frozenset({2}): {'weight': 1},
  frozenset({3}): {'weight': 1}},
 1: {frozenset({1, 2, 3}): {'weight': 1}}}
```
Cell of higher rank is proper subset of a cell of lower rank.

Please clarify is it a bug or am I wrong in something?

**Comment by mhajij** [comment]
@viyx this issue has been resolved. I am closing this issue.
