### ISSUE TITLE
Definition of CCC and the logic that follows from it. 

### ISSUE THREAD

**Issue by viyx** [pyt-team/TopoNetX#316]
Hello, when I add a duplicate cell into CCC (with the same nodes which has another cell) I see different logic. First time the proper set inclusion works, another time - just inclusion. Also there is the same ambiguity in docs.

The first code implies **proper set inclusion**, so it is imposible to have two or more cells of rank > 0 in CCC
```python
from toponetx.classes import CombinatorialComplex as CCC

example = CCC()

example.add_cell([1,2], rank=1)
example.add_cell([1,2], rank=2)

example.cells.hyperedge_dict
```
```
{1: {},
 0: {frozenset({1}): {'weight': 1}, frozenset({2}): {'weight': 1}},
 2: {frozenset({1, 2}): {'weight': 1}}}
```

The second code implies **usual set inclusion**, so it is possible to have two or more cells of rank > 0 in CCC
```python
from toponetx.classes import CombinatorialComplex as CCC

example = CCC()

example.add_cell([1], rank=1)
example.add_cell([1], rank=2)

example.cells.hyperedge_dict
```
```
{1: {frozenset({1}): {'weight': 1}},
 0: {frozenset({1}): {'weight': 1}},
 2: {frozenset({1}): {'weight': 1}}}
```

Also In doc and the article there is ambiguity:
**[docs](https://github.com/pyt-team/TopoNetX/blob/main/tutorials/03_combinatorial_complexes.ipynb)**

$[1]$ Let S be a non-empty finite set and $\mathcal{P}(S)$ its power set. A combinatorial complex (CCC) is a tuple $(X, \imath)$ formed by a set $X \subset \mathcal{P}(S)$ \ ${\emptyset}$ together with a rank function $\imath : X \rightarrow \mathbb{Z}^+$
that 

&emsp; (i) $\imath$(${x}$) $= 0$ for all $x \in S$, and 

&emsp; (ii) for all $x, y \in X$ , if $x \subsetneq y$ then $\imath (x) < \imath (y)$.

and in **[article](https://arxiv.org/abs/2206.00606)**
<img width="1095" alt="Screenshot 2023-11-12 at 08 09 26" src="https://github.com/pyt-team/TopoNetX/assets/25210142/587c6327-726a-4c6b-ab1b-301316851b8b">

Please clarify what logic I should expect in CCC, proper set inclusion rule or just set inclusion. Can cells (of rank 0 and more) be duplicated? And what is the definition of CCC?

**Comment by mhajij** [comment]
The definition has been related a little  in the new version to meet Def 9 here

![image](https://github.com/pyt-team/TopoNetX/assets/61298952/e9806510-5cc6-46f3-9b1c-6ad106b9d9d1)


![image](https://github.com/pyt-team/TopoNetX/assets/61298952/07e1e609-ced2-4074-b659-7553d578e3dd)


from toponetx.classes import CombinatorialComplex as CCC

example = CCC()

example.add_cell([1,2], rank=1)
example.add_cell([1,2], rank=2)

when you add the second cell, the first one gets deleted and replaced by the second one. 

You should access the cells with example.cells or example.skeleton(1) etc not with example.cells.hyperedge_dict

________

for the example 

from toponetx.classes import CombinatorialComplex as CCC

example = CCC()

example.add_cell([1], rank=1)
example.add_cell([1], rank=2)

I just made merged a PR to address this issue to make it match the definition above. Let me know if this answers your question so that I close this issue.

**Comment by viyx** [comment]
Thanks for the quick response. I got the exception from your code, now it's clear that there cant be the same _vertices_ and _cells_, _vertices_ are prioritorized.
<img width="1024" alt="Screenshot 2023-11-12 at 12 31 39" src="https://github.com/pyt-team/TopoNetX/assets/25210142/33243b8e-7e6f-4ea8-be1c-5d919930b73e">


As I can see, there is still a contradiction with Def 9. From Def 9 we can get  _cells_ of rank>0 which are the _vertices_(rank=0). Even so could you clarify what is the definition of CCC in this repository now, to undestand how to work with CCC properly?

**Comment by mhajij** [comment]
I'm not sure what behavior you are seeking. Can you be specific?
Def 9 implies that cells with single elements can only have rank 0. This is why an exception is given.

**Comment by viyx** [comment]
Oh, I see, there is no contradicton now, I was wrong in the previous post. No more questions, thanks

**Comment by viyx** [comment]
Sorry, I'm confused again)
 
 Is it legal CCC, where am I wrong?

Let S = {a,b,c}, X = {{a}, {bc}}, rk(a) = 3, rk(bc) = 1

It has vertice of rank=3 and at the same time satisfy Def 9.

**Comment by mhajij** [comment]
Hello,

No it's not legal. X is not valid here for ccc because it must contain all elements of S. Once that happens it cannot have a and in two different ranks, only the lower one, in this case rank zero.

**Comment by viyx** [comment]
Ok, I got that X is not valid, bad example from me

But this one looks legal
Let S = {a,b,c}, X = {{a}, {b}, {c}, {bc}}, rk(a) = rk(bc) = rk(b) = rk(c) = 3

**Comment by mhajij** [comment]
> Ok, I got that X is not valid, bad example from me
> 
> But this one looks legal Let S = {a,b,c}, X = {{a}, {b}, {c}, {bc}}, rk(a) = rk(bc) = rk(b) = rk(c) = 3
the defintion forces 

axiom 1 in def makes it impossible to create the above example/

rk(a) = rk(b) = rk(c) to be zero because they are singletons. All elements of S must have rank zero. Hence rk(b) and rk(c) cannot be 3.

**Comment by viyx** [comment]
> Ok, I got that X is not valid, bad example from me
> 
> But this one looks legal Let S = {a,b,c}, X = {{a}, {b}, {c}, {bc}}, rk(a) = rk(bc) = rk(b) = rk(c) = 3

What definition do you use? Acoording to this one
<img width="1095" alt="Screenshot 2023-11-12 at 08 09 26" src="https://github.com/pyt-team/TopoNetX/assets/25210142/587c6327-726a-4c6b-ab1b-301316851b8b">

Axiom 1 is satisfied, all singletons s in X
Axiom 2 is satisfied, 3 <= rk(bc) <= rk(b) <= rk(c) <= 3

**Comment by mhajij** [comment]
Ok I see the source of confusion. We actually consider remark 

![image](https://github.com/pyt-team/TopoNetX/assets/61298952/d61cc3c9-6d03-420e-a3c6-f9f5459f93c3)

for our implemenation which forces the singularities to have zero ranks.
In other words, in TopoNetX, you can assume that the definition is 9 + the remark above. So in your example, a valid CCC : 

rk(a) (must be) =0, rk(b) (must be) =0, rk(c) (must be) =0

**Comment by viyx** [comment]
Ok, and what is about axiom2, if I modify a bit my exmaple

Let S = {a,b,c}, X = {{a}, {b}, {c}, {bc}}, rk(a) = rk(bc) = rk(b) = rk(c) = 0

Again all axioms is satisfied, including remark 4.1

Axiom 1 is satisfied, all singletons s in X and their rank 0
Axiom 2 is satisfied, 0 <= rk(bc) <= rk(b) <= rk(c) <= 0
