### ISSUE TITLE
Changing lint and formatter

### ISSUE THREAD

**Issue by devendragovil** [pyt-team/TopoNetX#328]
# What

I am proposing changing the lint and formatter from black & flake8 to [ruff](https://github.com/astral-sh/ruff). 

# Why

1. It's significantly faster. 
2. I am seeing community migration away from black and flake8 to ruff in various projects. 
3. Single dependency for both lint and formatting. 

I would like your views on this.

**Comment by devendragovil** [comment]
@ffl096  What do you think?

**Comment by mhajij** [comment]
@ninamiolane I'm adding you to this discussion as well.

**Comment by ffl096** [comment]
I don't have any hands-on experience with ruff so far, but their project site looks promising. An initial pull request switching over to ruff (I guess it would entail more changes afterwards) would be welcome from my side :)

**Comment by mhajij** [comment]
If we decide to switch, just please remember that we need to do it consistently across the three packages.

**Comment by devendragovil** [comment]
@ffl096 I will raise a PR on Thursday, blocked for a couple of days.

@mhajij  Yes, noted. Will make sure to do that for all 3 packages.

**Comment by devendragovil** [comment]
I have a question regarding the current set up which is 
<img width="452" alt="image" src="https://github.com/pyt-team/TopoNetX/assets/39613474/716fe27f-d84e-4174-83b4-831b029d1f0e">

May I ask why we have chosen to ignore these particular test cases?
