### ISSUE TITLE
Typos and errors in [01_simplicial_complexes.ipynb]

### ISSUE THREAD

**Issue by rodroadl** [pyt-team/TopoNetX#349]
Hello, I was following [01_simplicial_complexes.ipynb](https://github.com/pyt-team/TopoNetX/blob/main/tutorials/01_simplicial_complexes.ipynb) and found some typo and errors. I can fix it and request PR, but I wanted to check if that is what you want.

| current | corrected |
| -------- | ---------- |
| Consider the unidrected | Consider the undirected |
| Example 2 graph is not showing | |
| \emph{abstract simplicial complex} is not rendered | |
| in the cell complex | in the simplicial complex |
| foruth | fourth |
| $[2,5][3,4]$ | $[2,5],[3,4]$ |
| equiavelnt | equivalent |
| lsit | list |
|defintions | definitions |
| faces/edge/vertices | faces/edges/vertices |

**Comment by ffl096** [comment]
Pull requests are of course more than welcome :)

**Comment by rodroadl** [comment]
Resolved with PR #350
