### ISSUE TITLE
Fix thumbnails for notebooks on doc website

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoNetX#84]
# What?

The tutorials webpage of the documentation website does not display the thumbnails properly. We should fix this.

https://pyt-team.github.io/toponetx/tutorials/index.html

# Why?

The tutorials webpage is one of the first pages that users see. It should look clean.

# Where?

The `nbsphinx_thumbnails` dictionary could be updated in:
https://github.com/pyt-team/TopoNetX/blob/main/docs/conf.py

Alternatively, the tag nbsphinx_thumbnails could be used directly in the jupyter notebook as meta data of a cell. Note that this would override the `nbsphinx_thumbnails` dictionary from conf.py

There is a difficulty emerging from the fact that the notebooks are loaded in docs/tutorials through the symlink notebooks.

# How?

Some information can be found on the website of `nbsphinx` which is the package used to create such thumbnails:
https://nbsphinx.readthedocs.io/en/0.9.1/gallery/thumbnail-from-conf-py.html

**Comment by devendragovil** [comment]
I found a way to enable the thumbnails. The PR #179  fixes this. However, I am not satisfied with the method used, I am trying to come up with a better method. The Symlink is indeed presenting a lot of issues.

**Comment by devendragovil** [comment]
@mhajij  @ninamiolane  PR #179  has fixed this issue.
