### ISSUE TITLE
Clean docstrings and API

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoNetX#95]
# What?

The names of functions, files, folders, variables, parameters needs a clean-up. For example:
- rank is sometimes refered as `r`, sometimes as `rank`,
- docstrings do not match the functions' signatures,
- a cell complex is abbreviated as "CX"; however in the papers Hajij 2023 and Papillon 2023 we use the abbreviation CC
- a combinatorial complex is abbreviated as "CC"; however in the papers Hajij 2023 and Papillon 2023 we use the abbreviation CCC
- etc

The docstrings do not always respect our [docstring conventions](https://pyt-team.github.io/toponetx/contributing/index.html#write-documentation), which renders poorly in the [documentation website](https://pyt-team.github.io/toponetx/index.html).

# How?

Clean docstrings in `toponetx/algorithms`:
- [ ] Check that they respect the correct formatting
- [ ] Check that the Parameters description match the function signature

Clean docstrings in `toponetx/classes`:
- [ ] Check that they respect the correct formatting
- [ ] Check that the Parameters description match the function signature

Clean docstrings in `toponetx/utils`:
- [ ] Check that they respect the correct formatting
- [ ] Check that the Parameters description match the function signature

Decide on abbreviation and apply changes:
- [x] Use CC instead of CX for cell complex, everywhere
- [x] Use CCC instead of CC for combinatorial complex, everywhere

Make sure that variable/parameter names are consistent:
- [x] Use `rank` for rank everywhere

**Comment by mhajij** [comment]
I started addressing this a little bit. I think the docstrings for algorithms is fine. No?

**Comment by mhajij** [comment]
@devendragovil 
@maneelusf 
@gurug-dev 

This is also a priority task. Can you please help?

**Comment by ninamiolane** [comment]
@ffl096 this is stalled issue. I have seen some PRs from you that were addressing it in the past. Could you check this issue's status? Maybe we can close it now? 🤞 Thanks!

**Comment by ffl096** [comment]
There are unfortunately still places that need to be cleaned up, though there was some progress in the past. Let's keep this open for now.

**Comment by ninamiolane** [comment]
@ffl096 would you have any update on this? Maybe we can close?
